### ISSUE TITLE
TypeError: Cannot read property 'email' of null

### ISSUE THREAD

**Issue by iRayanKhan** [edc1591/homebridge-bond#7]
Hello, I just installed this plugin with no bond fans set up idk if this is the issue, but if it is please lmk. My unit comes by Thursday.

#Config:
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "Homebridge",
	"accessories": [{
			"accessory": "Chamberlain",
			"name": "Double garage",
			"username": "khanrayan7088@gmail.com",
			"password": "Canada113",
			"deviceId": "xxx"
		},
		{
			"accessory": "Chamberlain",
			"name": "Single Garage",
			"username": "khanrayan7088@gmail.com",
			"password": "Canada113",
			"deviceId": "xxx"
		},
		{
			"accessory": "DummySwitch",
			"name": "Lights",
			"stateful": true
		},
		{
			"accessory": "SonyTV",
			"name": "TV",
			"mac": "xx",
			"ip": "10.0.0.xx",
			"tvsource": "tv:dvbs",
			"maxchannels": 500,
			"soundoutput": "speaker",
			"onscript": "/home/pi/scripts/dolbyon.sh",
			"offscript": "/home/pi/scripts/dolbyoff.sh",
			"savefilenameprefix": "/home/pi/sonycookie"

		},
		{
			"accessory": "DummySwitch",
			"name": "Living Room Lights",
			"stateful": true
		},
		{
			"accessory": "DummySwitch",
			"name": "Master BedRoom Lights",
			"stateful": true
		},
		{
			"accessory": "DummySwitch",
			"name": "BackYard Lights",
			"stateful": true
		}
	],
	"platforms": [{
		"platform": "Doorbell",
		"doorbells": [{
				"name": "Doorbell Front"
			},
			{
				"platform": "TplinkSmarthome",
				"name": "TplinkSmarthome",

				"devices": [{
						"host": "10.0.0.xx"
					},
					{
						"platform": "Bond",
						"email": "xx",
						"password": "xx"
					}


				]
			}
		]
	}]

}
```
And with this I get the error: 
Load homebridge-bond.Bond
/usr/local/lib/node_modules/homebridge-bond/dist/index.js:10
        let email = config['email'];
                          ^

TypeError: Cannot read property 'email' of null
    at new BondPlatform (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:10:27)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:347:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by plainsane** [comment]
You need to configure,your credentials for bond.

In your config, add the platforms,section and provide your Creds
"bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
        "platforms":[{
                    "platform": "Bond",
                    "email": "",
                    "password": ""
        }],
    "accessories": [

**Comment by iRayanKhan** [comment]
I have my credentials in there, just removed them so people don't login to my account

**Comment by iRayanKhan** [comment]
I have no fans synced with my bond, yet I just wanted to make sure the plugin works while my unit arrives Thursday. Is this why it may not be working?

**Comment by iRayanKhan** [comment]
OMG I got it I figured out why it wouldn't work. It had to be at the top of the platforms since it was trying to be a switch. Thanks for the reply!

**Comment by fancypants66** [comment]
I had a similar error but at a different location. Checked my config and even tried the version in config.example.json without success.
`Load homebridge-bond.Bond
/usr/lib/node_modules/homebridge-bond/dist/index.js:10
        let email = config['email'];
                          ^

TypeError: Cannot read property 'email' of null
    at new BondPlatform (/usr/lib/node_modules/homebridge-bond/dist/index.js:10:27)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:347:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:88:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
`
I know it's bad, but I did hardcode my email and pass in /usr/lib/node_modules/homebridge-bond/dist/index.js and it worked, so is there an error locating my config.json? or am I missing something else?
